[platformio]
default_envs = seeed-xiao-nrf54lm20a

[env:seeed-xiao-nrf54lm20a]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-nrf54lm20a
framework = zephyr
platform_packages =
    platformio/toolchain-gccarmnoneeabi@~1.90201.0
monitor_speed = 115200
